---

- hosts: localhost
  vars:
    df_home: '~/dotfiles'
  tasks:

#    - name: Show OS
#      debug:
#        var: ansible_distribution
#
    - name: Handle system dependencies
      package:
        name: '{{ item }}'
        state: latest
      with_items:
        - pylint
        - pyflakes
        - python-flake8
      when: ansible_distribution != 'MacOSX'

    - name: Clone live plugins
      git:
        repo:  '{{ item.repo }}'
        dest: '{{ df_home }}/{{ item.dest }}'
      with_items:
        - { 'nm': 'solarization', 'repo': 'https://github.com/altercation/solarized.git', 'dest': 'solarization' }
        - { 'nm': 'vim:pathogen', 'repo': 'https://github.com/tpope/vim-pathogen.git', 'dest': 'pathogen-dl' }
        - { 'nm': 'vim:sensible', 'repo': 'https://github.com/tpope/vim-sensible.git', 'dest': '.vim/bundle/vim-sensible' }
        - { 'nm': 'vim:syntastic', 'repo': 'https://github.com/vim-syntastic/syntastic.git', 'dest': '.vim/bundle/syntastic' }
        - { 'nm': 'vim:vim-obsession', 'repo': 'https://github.com/tpope/vim-obsession.git', 'dest': '.vim/bundle/vim-obsession' }
        - { 'nm': 'tmux:tpm', 'repo': 'https://github.com/tmux-plugins/tpm', 'dest': '.tmux/plugins/tpm' }
        - { 'nm': 'tmux:sensible', 'repo': 'https://github.com/tmux-plugins/tmux-sensible', 'dest': '.tmux/plugins/tmux-sensible' }
        - { 'nm': 'tmux:resurrect', 'repo': 'https://github.com/tmux-plugins/tmux-resurrect', 'dest': '.tmux/plugins/tmux-resurrect' }
        # meh - { 'nm': 'tmux:sidebar', 'repo': 'https://github.com/tmux-plugins/tmux-sidebar', 'dest': '.tmux/plugins/tmux-sidebar' }
        - { 'nm': 'tmux:continuum', 'repo': 'https://github.com/tmux-plugins/tmux-continuum', 'dest': '.tmux/plugins/tmux-continuum' }



      loop_control:
        label: '{{ item.nm }}'

    - name: Link as necessary
      file:
        path: '{{ item.path }}'
        src: '{{ item.src }}'
        state: link
      with_items:
        - { 'nm': 'pathogen', 'src': '{{ df_home }}/pathogen-dl/autoload/pathogen.vim', 'path': '{{ df_home }}/.vim/autoload/pathogen.vim' } 
        - { 'nm': 'vim-solarized-lt', 'src': '{{ df_home }}/solarization/vim-colors-solarized', 'path': '{{ df_home }}/.vim/bundle/vim-colors-solarized' }
      loop_control:
        label: '{{ item.nm }}'


    - name: Manage solarization file for tmux - light
      blockinfile:
        dest: '{{ item.path }}'
        block: |
            {{ lookup( 'file', '{{ df_home }}/solarization/tmux/tmuxcolors-light.conf' ) }}
      with_items:
        - { 'nm': 'laptop', 'path': '{{ df_home }}/tmux-conf-laptop.conf' }
        - { 'nm': 'jump', 'path': '{{ df_home }}/tmux-conf-jump.conf' }
      loop_control:
        label: '{{ item.nm }}'

    - name: Manage pathogen block
      blockinfile:
          dest: '{{ item.path }}'
          marker: '" ## {mark} ANSIBLE MGD: PATHOGEN'
          block: | 
            execute pathogen#infect()
            syntax on
            filetype plugin indent on
      with_items:
        - { 'nm': 'pathogen .vimrc block', 'path': '{{ df_home }}/.vimrc' }
      loop_control:
        label: '{{ item.nm }}'

    - name: Manage solarized
      blockinfile:
          dest: '{{ item.path }}'
          marker: '" ## {mark} ANSIBLE MGD: SOLARIZED'
          block: | 
            syntax enable
            set background=light
            colorscheme solarized
      with_items:
        - { 'nm': 'solarized .vimrc block', 'path': '{{ df_home }}/.vimrc' }
      loop_control:
        label: '{{ item.nm }}'

#    - name: Manage tmux-resurrect
#      blockinfile:
#          dest: '{{ item.path }}'
#          marker: '" ## {mark} ANSIBLE MGD: PATHOGEN'
#          block: | 
#            execute pathogen#infect()
#            syntax on
#            filetype plugin indent on
#      with_items:
#        - { 'nm': 'pathogen .vimrc block', 'path': '{{ df_home }}/.vimrc' }
#      loop_control:
#        label: '{{ item.nm }}'

    - name: Finish vim-obsession install
      command: 'vim -u NONE -c "helptags vim-obsession/doc" -c q'

