---

- hosts: localhost
  vars:
    df_home: '~/dotfiles'
  tasks:
    - name: Clone syntastic
      git:
        repo:  'https://github.com/vim-syntastic/syntastic.git'
        dest: '{{ df_home }}/{{ item.dest }}'
      with_items:
        - { 'nm': 'vim:syntastic', 'repo': 'https://github.com/vim-syntastic/syntastic.git', 'dest': '.vim/bundle/syntastic' }
      loop_control:
        label: '{{ item.nm }}'

